apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ../infra/k8s-google-cloud/*
build:
  googleCloudBuild:
    projectId: micro-dev-301819
  artifacts:
    - image: eu.gcr.io/micro-dev-301819/auth
      context: ../auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .


    - image: eu.gcr.io/micro-dev-301819/tickets
      context: ../tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/micro-dev-301819/orders
      context: ../orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/micro-dev-301819/expiration
      context: ../expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/micro-dev-301819/payments
      context: ../payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: eu.gcr.io/micro-dev-301819/client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
